TimeBasedMedia fields for Cataloging
collectionspace/application pull request #226
Opened 2022-05-02 20:50 UTC by mikejritter

Fields + vocab defined in:
* https://collectionspace.atlassian.net/browse/DRYD-1034
* https://collectionspace.atlassian.net/browse/DRYD-1039
* https://collectionspace.atlassian.net/browse/DRYD-1040
* https://collectionspace.atlassian.net/browse/DRYD-1041

# Notes

There are still some missing vocabulary entries in the specs from the epic (https://collectionspace.atlassian.net/browse/DRYD-1033), so I've only added placeholders for them. These are: `softwarelibraries`, `connectiontype`, `domaintype`, `requiredapplication`, `compressionstandards`, and `colortypes`.

There's also a controlled list defined in the spec for saying something is required, which is typically just a yes/no. I was considering just using a single vocab item for this but wasn't sure what is preferred.

2022-05-05 22:45 UTC, ray-lee requested changes
Looks fine, but I think there are some typos in option value display names.

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +			<option id="documentationcopy">documentationch copy</option>
Typo in the display name?

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +			<option id="accesscode">accesscode</option>
Missing a space in the display name?

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +      <option id="doublemono">doublemono</option>
Missing space in display name?

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +      <option id="3channelmono">3channelmono</option>
Missing space in display name?

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +      <option id="nosound">nosound</option>
Missing space in display name?

2022-05-05 22:45 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
>  </instances>
See comments in above file. Typos will need to be fixed in this file too.

2022-05-05 22:47 UTC, ray-lee commented
If the yes/no values aren't expected to change independently in different fields, it's better to have just one list. If they're not expected to change at all, there is already a yes/no static option list used by a number of fields. I'd ask Megan how volatile she thinks these lists will be.

2022-05-05 22:49 UTC, ray-lee commented
Note: I did not check this configuration against the definitions in the JIRA issues. I only reviewed for configuration errors.

2022-05-06 18:37 UTC, mikejritter commented
@ray-lee I pushed a commit to fix the typos but there are some inconsistencies between the specs/wireframes I think we'll need to resolve as well (from my other comment on the cspace-ui PR).

2022-05-11 22:43 UTC, mikejritter commented
@ray-lee I removed the yes/no values in favor of the static options you mentioned. I also made some small updates to align field names more with what is in the spec, hopefully didn't miss anything.

2022-05-13 21:39 UTC, ray-lee commented
Looks good!

2022-05-13 21:39 UTC, merged