DRYD-1065: Copyright extension for collectionobject
collectionspace/application pull request #235
Opened 2022-09-02 19:15 UTC by mikejritter

Jira: https://collectionspace.atlassian.net/browse/DRYD-1065

2022-09-23 18:22 UTC, mikejritter commented on tomcat-main/src/main/resources/defaults/base-collectionobject.xml
> +			<field id="rightJurisdiction" autocomplete="true" ui-type="enum" />
Ah, I missed that on the wireframe - the spec had it as a controlled list which is what I had been following. The description of the field makes it sound like it should maybe be a place instead?

2022-09-23 18:33 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-collectionobject.xml
> +			<field id="rightJurisdiction" autocomplete="true" ui-type="enum" />
I'm not sure. There is a country dynamic term list, so maybe it's supposed to be that? We might need to have Jessi ask Megan what she wanted.

2022-10-04 00:02 UTC, ray-lee requested changes
This just needs the change to `rightJurisdiction`, and conflicts resolved.

2022-10-04 00:02 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-collectionobject.xml
> +			<field id="rightJurisdiction" autocomplete="true" ui-type="enum" />
Since this is now a static term list, `autocomplete` and `ui-type` should be removed.

2022-10-04 17:22 UTC, mikejritter commented
@ray-lee I updated the `rightJurisdiction` field though I'm not sure if I've been doing that for other static lists :sweat_smile:. Also resolved the conflict on master so this should be good to merge.

2022-10-04 21:40 UTC, ray-lee commented
@mikejritter The `autocomplete="true"` tells the system that the field contains a reference to another record (a ref name). It really should be called `isRef` or something like that. If you set it to true on a field that doesn't contain a ref name, it's mostly fine, but it will cause the system to do extra work. For example, it will need to look in the field when it populates the Terms Used sidebar.

2022-10-04 21:40 UTC, ray-lee approved these changes

2022-10-04 21:41 UTC, merged