DRYD-1246: UCB Held In Trust Contribution
collectionspace/application pull request #266
Opened 2023-09-11 20:56 UTC by mikejritter

**What does this do?**
* Adds Held In Trust procedure and vocabs

**Why are we doing this? (with JIRA link)**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1246

This brings in the Held in Trust contribution from ucb contribution branch.

**How should this be tested? Do these changes have associated tests?**
The services and application layer can be quickly tested by running the integration test suite:
* Build with the corresponding PR from the application layer and the necessary tenants enabled to run the Integration Tests
* Start collection space
* Run the integration tests, e.g. `[services] $ mvn test`

**Dependencies for merging? Releasing to production?**
* The services layer PR: https://github.com/collectionspace/services/pull/363

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@mikejritter ran the integration tests successfully

2023-10-04 18:57 UTC, remillet approved these changes

2023-11-10 23:41 UTC, ray-lee requested changes
This needs some changes. In general, `hit` needs to be changed to `heldintrust`, and `hits` to `heldintrusts` (adjust case as needed for the prevailing convention in each usage).

Also see comments below.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +		<web-url>handlinglimitationslevels</web-url>
Probably should be `handlinglimitationlevels` (there was an extra s).

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +		<title-ref>handlinglimitationslevels</title-ref>
Probably should be `handlinglimitationlevels` (there was an extra s).

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +		<web-url>handlinglimitationstypes</web-url>
Probably should be `handlinglimitationtypes ` (there was an extra s).

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +		<title-ref>handlinglimitationstypes</title-ref>
Probably should be `handlinglimitationtypes ` (there was an extra s).

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +			<option id="hl_handlinggender">handling:gender</option>
Missing space? Seems like it should be `handling: gender`.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> +			<option id="hl_handlingother">handling:other</option>
Missing space? Seems like it should be `handling: other`.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +  <tab-url>hit-tab</tab-url>
I don't think `web-url` and `tab-url` are used any more. They can be removed.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +      <field id="agreementStatusNote" ui-search="repeatable" />
`ui-search` isn't used any more. It can be removed from the above three lines.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +      <field id="agreementRenewalDate" datatype="date" ui-search="repeatable" />
Remove `ui-search`.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +    <field id="entryReason" autocomplete="true" ui-type="enum" />
This has `autocomplete="true" ui-type="enum"`, but it is bound to a static option list in the UI. Either these attributes should be removed, or it should be bound to a dynamic term list.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +      <field id="internalApprovalGroupName" autocomplete="true" />
Needs `ui-type="enum"`, since it is bound to a term list, not an autocomplete.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +      <field id="externalApprovalGroupName" autocomplete="true" />
Needs `ui-type="enum"`, since it is bound to a term list, not an autocomplete.

2023-11-10 23:41 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-procedure-hit.xml
> +      <field id="correspondenceReference" ui-type="enum" />
This is free text in the UI, so remove `ui-type="enum"` (which I don't think would do anything anyway, without `autocomplete="true"` also being present.).

2023-11-15 21:45 UTC, mikejritter commented
@ray-lee `hit` to `heldintrust` renaming is done. I also opted to create a vocab for the entry reasons in order to not use the static list on the ui side. I prefaced it with `Held-in-Trust` as the previous one comes from intake.

2023-12-09 01:07 UTC, ray-lee approved these changes
Looks good.

2023-12-09 01:07 UTC, merged