DRYD-1436: Add related link group
collectionspace/application pull request #290
Opened 2024-07-31 16:33 UTC by mikejritter

**What does this do?**
* Add related link group to collectionobject

**Why are we doing this? (with JIRA link)**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1436

This adds related links to the reference information section for collectionobjects.

**How should this be tested? Do these changes have associated tests?**
* Rebuild collectionspace
* Using the related cspace-ui PR: 
  * Create a collectionobject and scroll to the Reference Information section
  * See that the related link group exists and can be filled out
  * Switch to the public browser template and see the same as the above

**Dependencies for merging? Releasing to production?**
None

**Has the application documentation been updated for these changes?**
No

**Did someone actually run this code to verify it works?**
@mikejritter tested locally

2024-08-06 14:01 UTC, ray-lee requested changes
There seems to be a discrepancy in field names between application and UI.

2024-08-06 14:01 UTC, ray-lee commented on tomcat-main/src/main/resources/defaults/base-collectionobject.xml
> +			<field id="relatedURL" />
In the UI, this is called `relatedLink`.

2024-08-12 18:56 UTC, mikejritter commented on tomcat-main/src/main/resources/defaults/base-collectionobject.xml
> +		<repeat id="relatedLinkGroupList/relatedLinkGroup">
Looks like I never pushed my commit, these should have been `publishedRelatedLink` to be aligned with the ui.

2024-08-13 15:59 UTC, ray-lee approved these changes
Looks good.

2024-08-13 15:59 UTC, merged